// AUTO-GENERATED by contracts/script/sync-abi.sh — do not edit by hand.
// Source: contracts/deployments/*.json (written by script/Deploy.s.sol)

export const deployments: Record<number, `0x${string}`> = {
  31337: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  46630: "0x87279BFB3BD7f1d4338bB860612a96a1D9A67cF3",
};
