#!/usr/bin/env bash
# Export the compiled ABI and the deployed addresses into the frontend.
#
# The EVM analogue of `excute_idl_update.sh`, which copied the Anchor IDL into
# `app/lib/idl/`. An ABI is to a Solidity contract what an IDL is to an Anchor
# program: the machine-readable interface the client builds calls from.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$HERE/../app/lib/evm"
OUT="$HERE/out/VaultInheritance.sol/VaultInheritance.json"

command -v jq >/dev/null || { echo "jq is required"; exit 1; }
[ -f "$OUT" ] || { echo "Build first: forge build"; exit 1; }
mkdir -p "$APP_DIR"

{
  echo "// AUTO-GENERATED by contracts/script/sync-abi.sh — do not edit by hand."
  echo "// Source: contracts/out/VaultInheritance.sol/VaultInheritance.json"
  echo "//"
  echo "// \`as const\` is load-bearing: it is what lets viem/wagmi infer argument"
  echo "// and return types for every function at compile time, which is the EVM"
  echo "// equivalent of the generated \`VaultInheritance\` type Anchor produced"
  echo "// from the IDL."
  echo ""
  # No newline between the array and `as const`: TypeScript forbids a line
  # terminator before `as`, so `jq`'s trailing newline would break the file.
  printf 'export const vaultInheritanceAbi = %s as const;\n' "$(jq -c '.abi' "$OUT")"
  echo ""
  echo "export type VaultInheritanceAbi = typeof vaultInheritanceAbi;"
} > "$APP_DIR/abi.ts"

# Deployed addresses, keyed by chain id.
{
  echo "// AUTO-GENERATED by contracts/script/sync-abi.sh — do not edit by hand."
  echo "// Source: contracts/deployments/*.json (written by script/Deploy.s.sol)"
  echo ""
  echo "export const deployments: Record<number, \`0x\${string}\`> = {"
  for f in "$HERE"/deployments/*.json; do
    [ -e "$f" ] || continue
    cid=$(jq -r '.chainId' "$f")
    addr=$(jq -r '.address' "$f")
    echo "  $cid: \"$addr\","
  done
  echo "};"
} > "$APP_DIR/deployments.ts"

echo "wrote $APP_DIR/abi.ts"
echo "wrote $APP_DIR/deployments.ts"
